apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollem-next-00-deployment
spec:
  selector:
    matchLabels:
      app: rollem-next
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '8081'
      labels:
        app: rollem-next
    spec:
      containers:
      - name: rollem-next-00
        image: lemtzas/rollem-discord:2.8.3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 200m
            memory: 400M
        env:
        - name: 'reboot'
          value: '2022-12-07'
        - name: DISCORD_BOT_SHARD_ID
          value: '0'
        - name: DISCORD_BOT_SHARD_COUNT
          value: '2'
        - name: 'DISCORD_BOT_USER_TOKEN'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: DISCORD_BOT_USER_TOKEN
        - name: 'APPINSIGHTS_CONNECTIONSTRING'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: APPINSIGHTS_CONNECTIONSTRING
        - name: 'DEFER_TO_CLIENT_IDS'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: DEFER_TO_CLIENT_IDS
        - name: 'DB_CONNECTION_STRING'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: DB_CONNECTION_STRING