apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollem-next-deployment
spec:
  selector:
    matchLabels:
      app: rollem-next
  replicas: 1
  template:
    metadata:
      labels:
        app: rollem-next
    spec:
      containers:
      - name: rollem
        image: lemtzas/rollem-discord:2.4.37
        #imagePullPolicy: Never
        env:
        - name: 'reboot'
          value: '2021-05-15.1'
        - name: 'DISCORD_BOT_USER_TOKEN'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: DISCORD_BOT_USER_TOKEN
        - name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: APPINSIGHTS_INSTRUMENTATIONKEY
        - name: 'DEFER_TO_CLIENT_IDS'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: DEFER_TO_CLIENT_IDS
        - name: 'DB_CONNECTION_STRING'
          valueFrom:
            secretKeyRef:
              name: rollem-next
              key: DB_CONNECTION_STRING