apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollem-prod-13-deployment
spec:
  selector:
    matchLabels:
      app: rollem-prod
  replicas: 1
  template:
    metadata:
      labels:
        app: rollem-prod
    spec:
      containers:
      - name: rollem-shard-13
        image: lemtzas/rollem-discord:2.4.39
        resources:
          requests:
            cpu: 150m
            memory: 250M
        env:
        - name: 'reboot'
          value: '2021-04-20'
        - name: DISCORD_BOT_SHARD_ID
          value: '13'
        - name: DISCORD_BOT_SHARD_COUNT
          value: '40'
        - name: 'DISCORD_BOT_USER_TOKEN'
          valueFrom:
            secretKeyRef:
              name: rollem-prod-2
              key: DISCORD_BOT_USER_TOKEN
        - name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
          valueFrom:
            secretKeyRef:
              name: rollem-prod-2
              key: APPINSIGHTS_INSTRUMENTATIONKEY
        - name: 'DEFER_TO_CLIENT_IDS'
          valueFrom:
            secretKeyRef:
              name: rollem-prod-2
              key: DEFER_TO_CLIENT_IDS
        - name: 'DB_CONNECTION_STRING'
          valueFrom:
            secretKeyRef:
              name: rollem-prod-2
              key: DB_CONNECTION_STRING