
## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring

  # Based on https://www.digitalocean.com/community/tutorials/how-to-set-up-digitalocean-kubernetes-cluster-monitoring-with-helm-and-prometheus-operator
  persistence:
    enabled: true
    existingClaim: pvc-9ddc6696-01b1-4c4e-8c58-09c22ce596fa
    storageClassName: do-block-storage
    accessModes: ["ReadWriteOnce"]
    size: 10Gi

  useStatefulSet: true

  ## Passed to grafana subchart and used by servicemonitor below
  ##
  service:
    portName: http-web

    nodeSelector:
      doks.digitalocean.com/node-pool: pool-monitoring
