
## Configuration for kube-state-metrics subchart
##
kube-state-metrics:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring
  prometheus:
    monitor:
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-monitoring

