## Configuration for prometheus-node-exporter subchart
##
prometheus-node-exporter:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring
  prometheus:
    monitor:
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-monitoring
