
## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  ## Admission webhook support for PrometheusRules resources added in Prometheus Operator 0.30 can be enabled to prevent incorrectly formatted
  ## rules from making their way into prometheus and potentially preventing the container from starting
  admissionWebhooks:
    patch:
      nodeSelector:
        doks.digitalocean.com/node-pool: pool-monitoring

  ## Resource limits & requests
  ##
  resources: {}
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

  ## Define which Nodes the Pods are scheduled on.
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring
