
## Component scraping the kube api server
kubeApiServer:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring

## Component scraping the kubelet and kubelet-hosted cAdvisor
kubelet:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring

## Component scraping the kube controller manager
kubeControllerManager:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring

## Component scraping coreDns. Use either this or kubeDns
coreDns:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring

## Component scraping kubeDns. Use either this or coreDns
kubeDns:
  serviceMonitor:
    nodeSelector:
      doks.digitalocean.com/node-pool: pool-monitoring

## Component scraping etcd
kubeEtcd:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring
  serviceMonitor:
    nodeSelector:
      doks.digitalocean.com/node-pool: pool-monitoring

## Component scraping kube scheduler
kubeScheduler:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring
  serviceMonitor:
    nodeSelector:
      doks.digitalocean.com/node-pool: pool-monitoring

## Component scraping kube proxy
##
kubeProxy:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring
  serviceMonitor:
    nodeSelector:
      doks.digitalocean.com/node-pool: pool-monitoring

## Component scraping kube state metrics
##
kubeStateMetrics:
  nodeSelector:
    doks.digitalocean.com/node-pool: pool-monitoring
