## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
alertmanager:
  config:
    receivers:
    # - name: 'null'
    - name: 'discord'
      slack_configs:
      - channel: '#alerts'
        api_url: 'https://discord.com/api/webhooks/NUMBER/SECRET/slack'
        text: |-
          {{- $root := . -}}
          {{ range .Alerts }}
            `{{ .Labels.severity }}` {{ .Annotations.summary }}
          {{ end }}


    templates:
    - '/etc/alertmanager/config/*.tmpl'